### ISSUE TITLE
Tweet not found

### ISSUE THREAD

**Issue by XahidEx** [vercel-labs/next-tweet#134]
Tweet not found, even though It exist. No tweets are being rendered. 
![image](https://github.com/vercel/react-tweet/assets/88249321/0aea32d7-a4f9-440b-aebf-77f3e7e5ab8e)

**Comment by nekochan0122** [comment]
Same here, it's only happened on Vercel, local it's fine.

**Comment by gonstoll** [comment]
Getting the same here. Working locally, not working on Vercel

**Comment by panayiotis** [comment]
It works on localhost and vercel edge.  
My guess is that cdn.syndication.twimg.com where the tweets are fetched from, might be blocking some vercel / AWS IP ranges.

A workaround is:
* get the tweet json from `https://react-tweet.vercel.app/api/tweet/${tweet_id}`
* store the file locally in order to avoid future cdn.syndication.twimg.com outages on build time
* use `<EmbeddedTweet tweet={tweet_json.data} />` instead of `<Tweet id={id}/>`

**Comment by nekochan0122** [comment]
@panayiotis It's working, Thank you so much.

https://blog.nekochantw.xyz/posts/hello-world#twitter
![image](https://github.com/vercel/react-tweet/assets/47508893/f23a4564-c818-47e6-9ab8-00b21185377f)

**Comment by Fardeen-Awais** [comment]
Check the solution: https://github.com/vercel/react-tweet/issues/137#issuecomment-2036823051
